if(!process.env.CLOUDFLARE)require('dotenv').config();
const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const speakeasy=require('speakeasy');const db=require('./db');const {encrypt}=require('./crypto-util');const connectors=require('./connectors');
const JWT_SECRET=process.env.JWT_SECRET;if(!JWT_SECRET||JWT_SECRET.length<32)throw new Error('JWT_SECRET must be at least 32 characters');
const loginAttempts=new Map();const BOARDS=['ROOM_ONLY','BED_AND_BREAKFAST','HALF_BOARD','FULL_BOARD','ALL_INCLUSIVE'];const jsonHeaders={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{...jsonHeaders,...extra}})}function htmlHeaders(){return{'content-type':'text/html; charset=utf-8'}}
function parseCookies(req){const out={};for(const part of(req.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function cookieHeader(name,value,opts={}){let s=`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax`;if(opts.maxAge!=null)s+=`; Max-Age=${Math.floor(opts.maxAge/1000)}`;if(opts.secure)s+='; Secure';return s}
function validSearch({destination,checkin,checkout,guests,rooms,board}){return!!destination&&destination.length<=150&&/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(checkin)&&/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(checkout)&&new Date(checkout)>new Date(checkin)&&Number.isInteger(Number(guests))&&Number(guests)>=1&&Number(guests)<=30&&Number.isInteger(Number(rooms))&&Number(rooms)>=1&&Number(rooms)<=20&&BOARDS.includes(board)}
function fill(t,p){return t?.replaceAll('{destination}',encodeURIComponent(p.destination)).replaceAll('{checkin}',p.checkin).replaceAll('{checkout}',p.checkout).replaceAll('{guests}',p.guests).replaceAll('{rooms}',p.rooms).replaceAll('{board}',p.board)||null}
async function body(req){if(!req.body)return{};const text=await req.text();if(text.length>100000)throw new Error('Body too large');try{return text?JSON.parse(text):{}}catch{throw new Error('Invalid JSON')}}
function auth(req){const token=parseCookies(req).session;if(!token)return null;try{return jwt.verify(token,JWT_SECRET)}catch{return null}}function allowed(role,...roles){return roles.includes(role)}
function rateLimited(req){const key=req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')||'unknown';const now=Date.now();const a=(loginAttempts.get(key)||[]).filter(t=>t>now-15*60*1000);if(a.length>=10){loginAttempts.set(key,a);return true}a.push(now);loginAttempts.set(key,a);return false}
function base32ToBytes(input){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';const clean=String(input||'').replace(/=+$/,'').toUpperCase().replace(/\s+/g,'');let bits=0,value=0,out=[];for(const ch of clean){const n=alphabet.indexOf(ch);if(n<0)throw new Error('Invalid 2FA secret');value=(value<<5)|n;bits+=5;if(bits>=8){bits-=8;out.push((value>>bits)&255)}}return new Uint8Array(out)}
async function verifyTotp(secret,token){const code=String(token||'').replace(/\s/g,'');if(!/^\d{6}$/.test(code))return false;const key=await crypto.subtle.importKey('raw',base32ToBytes(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']);const step=Math.floor(Date.now()/1000/30);for(let offset=-1;offset<=1;offset++){const counter=step+offset;const data=new ArrayBuffer(8);const view=new DataView(data);view.setUint32(0,Math.floor(counter/4294967296));view.setUint32(4,counter>>>0);const mac=new Uint8Array(await crypto.subtle.sign('HMAC',key,data));const index=mac[mac.length-1]&15;const bin=((mac[index]&127)<<24)|(mac[index+1]<<16)|(mac[index+2]<<8)|mac[index+3];if(String(bin%1000000).padStart(6,'0')===code)return true}return false}
async function handleApi(req,url){const method=req.method;const path=url.pathname;const staff=auth(req);
 if(path==='/api/auth/login'&&method==='POST'){if(rateLimited(req))return json({error:'Too many login attempts. Please try again later.'},429);try{const{username,password}=await body(req);if(typeof username!=='string'||typeof password!=='string')return json({error:'Invalid login'},400);const r=await db.query('SELECT * FROM staff WHERE username=$1',[username]);const s=r.rows[0];if(!s||!await bcrypt.compare(password,s.password_hash))return json({error:'Invalid username or password'},401);const temp=jwt.sign({staffId:s.id,purpose:'2fa'},JWT_SECRET,{expiresIn:'5m'});return json({tempToken:temp,needs2fa:true})}catch(e){console.error(e);return json({error:'Login service error'},500)}}
 if(path==='/api/auth/verify-2fa'&&method==='POST'){if(rateLimited(req))return json({error:'Too many login attempts. Please try again later.'},429);try{const{tempToken,code}=await body(req);let temp;try{temp=jwt.verify(String(tempToken||''),JWT_SECRET)}catch{return json({error:'Login expired, start again'},401)}if(!temp||temp.purpose!=='2fa'||!temp.staffId)return json({error:'Login expired, start again'},401);const r=await db.query('SELECT id,username,role,totp_secret FROM staff WHERE id=$1',[temp.staffId]);const s=r.rows[0];if(!s||!(await verifyTotp(s.totp_secret,code)))return json({error:'Invalid authenticator code'},401);const session=jwt.sign({staffId:s.id,username:s.username,role:s.role},JWT_SECRET,{expiresIn:'8h'});return json({ok:true,username:s.username,role:s.role},200,{'set-cookie':cookieHeader('session',session,{maxAge:8*3600*1000,secure:true})})}catch(e){console.error(e);return json({error:'2FA service error'},500)}}
 if(path==='/api/auth/logout'&&method==='POST'){if(!staff)return json({error:'Not logged in'},401);return json({ok:true},200,{'set-cookie':cookieHeader('session','',{maxAge:0,secure:true})})}
 if(path==='/api/auth/me'&&method==='GET'){if(!staff)return json({error:'Not logged in'},401);return json({username:staff.username,role:staff.role})}
 if(!staff)return json({error:'Not logged in'},401);
 if(path==='/api/sources'&&method==='GET'){const r=await db.query("SELECT id,name,login_url,deep_link_template,site_username,connector_type,enabled,last_error,last_checked_at FROM sources WHERE enabled=true OR connector_type IN ('browser','playwright') ORDER BY name");return json(r.rows.map(x=>({...x,site_username: x.connector_type==='browser'||x.connector_type==='playwright'?undefined:x.site_username})))}
 if(path==='/api/connectors'&&method==='GET')return json(connectors.configuredConnectors());
 if(path==='/api/admin/sources'&&method==='GET'){if(!allowed(staff.role,'SUPER_ADMIN','ADMIN'))return json({error:'Insufficient permissions'},403);const r=await db.query('SELECT id,name,login_url,deep_link_template,site_username,connector_type,enabled,browser_config,site_password_enc,last_error,last_checked_at FROM sources ORDER BY name');return json(r.rows.map(x=>({...x,hasPassword:!!x.site_password_enc,site_password_enc:undefined})))}
 if(path==='/api/sources'&&method==='POST'){if(!allowed(staff.role,'SUPER_ADMIN','ADMIN'))return json({error:'Insufficient permissions'},403);try{const{name,login_url,deep_link_template,site_username,site_password,agent_code,connector_type='api',enabled=true,browser_config={}}=await body(req);if(!name||!login_url)return json({error:'Name and login URL are required'},400);try{new URL(login_url)}catch{return json({error:'Invalid login URL'},400)}if(!['api','browser','playwright','manual'].includes(connector_type))return json({error:'Invalid connector type'},400);if(connector_type==='browser'||connector_type==='playwright'){if(!site_username||!site_password)return json({error:'Browser connector requires username and password'},400);if(typeof browser_config!=='object'||Array.isArray(browser_config))return json({error:'browser_config must be an object'},400)}const r=await db.query('INSERT INTO sources(name,login_url,deep_link_template,site_username,site_password_enc,agent_code,connector_type,enabled,browser_config) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[name.slice(0,120),login_url,deep_link_template||'',site_username||'',encrypt(site_password||''),agent_code||'',connector_type,Boolean(enabled),JSON.stringify(browser_config||{})]);return json({id:r.rows[0].id})}catch(e){console.error(e);return json({error:'Could not save source. Please check the source details and try again.'},500)}}
 if(path.startsWith('/api/sources/')&&method==='DELETE'){if(!allowed(staff.role,'SUPER_ADMIN','ADMIN'))return json({error:'Insufficient permissions'},403);await db.query('DELETE FROM sources WHERE id=$1',[path.split('/').pop()]);return json({ok:true})}
 if(path==='/api/search'&&method==='POST'){try{const{destination,checkin,checkout,guests,rooms=1,board='ROOM_ONLY'}=await body(req);if(!validSearch({destination,checkin,checkout,guests,rooms,board}))return json({error:'Check destination, dates, guests, rooms and board'},400);const r=await db.query('INSERT INTO searches(staff_id,destination,checkin,checkout,guests,rooms,board) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[staff.staffId,destination.trim(),checkin,checkout,Number(guests),Number(rooms),board]);const s=await db.query('SELECT id,name,login_url,deep_link_template,site_username,site_password_enc,agent_code,connector_type,enabled,browser_config FROM sources ORDER BY name');const connectorResult=await connectors.searchAll({destination:destination.trim(),checkin,checkout,guests:Number(guests),rooms:Number(rooms),board},s.rows);return json({searchId:r.rows[0].id,results:connectorResult.results,connectorStatuses:connectorResult.statuses,links:s.rows.map(x=>({sourceId:x.id,name:x.name,url:fill(x.deep_link_template,{destination,checkin,checkout,guests,rooms,board})||x.login_url}))})}catch(e){console.error(e);return json({error:'Search could not be completed'},500)}}
 if(path==='/api/history'&&method==='GET'){const isAdmin=['SUPER_ADMIN','ADMIN','MANAGER'].includes(staff.role);const q=isAdmin?'SELECT searches.*,staff.username FROM searches JOIN staff ON staff.id=searches.staff_id ORDER BY created_at DESC LIMIT 100':'SELECT searches.*,staff.username FROM searches JOIN staff ON staff.id=searches.staff_id WHERE staff_id=$1 ORDER BY created_at DESC LIMIT 100';const r=await db.query(q,isAdmin?[]:[staff.staffId]);return json(r.rows)}
 if(path.startsWith('/api/comparisons/')&&method==='GET')return json([]);if(path.startsWith('/api/comparisons/')&&method==='DELETE')return json({ok:true});return json({error:'Not found'},404)}
const initPromise=db.init();initPromise.catch(e=>console.error(e));async function handleRequest(req){const url=new URL(req.url);if(url.pathname==='/health'){try{await db.query('SELECT 1');return json({ok:true})}catch(e){console.error(e);return json({ok:false},503)}}if(url.pathname.startsWith('/api/')){try{return await handleApi(req,url)}catch(e){console.error(e);return json({error:'Request failed'},500)}}return new Response('Not found',{status:404,headers:htmlHeaders()})}
module.exports={handleRequest,initPromise};