require('dotenv').config();
const express=require('express'), cookieParser=require('cookie-parser'), bcrypt=require('bcryptjs'), jwt=require('jsonwebtoken'), speakeasy=require('speakeasy'), helmet=require('helmet'), rateLimit=require('express-rate-limit');
const db=require('./db'); const {encrypt}=require('./crypto-util');
const app=express(); app.disable('x-powered-by'); app.set('trust proxy',1); app.use(helmet({crossOriginResourcePolicy:false})); app.use(express.json({limit:'100kb'})); app.use(cookieParser()); app.use(express.static('public'));
const JWT_SECRET=process.env.JWT_SECRET; if(!JWT_SECRET||JWT_SECRET.length<32) throw new Error('JWT_SECRET must be at least 32 characters');
const pending=new Map();
const loginLimit=rateLimit({windowMs:15*60*1000,max:10,standardHeaders:true,legacyHeaders:false});
function auth(req,res,next){const t=req.cookies.session;if(!t)return res.status(401).json({error:'Not logged in'});try{req.staff=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:'Session expired, please log in again'})}}
function roles(...allowed){return (req,res,next)=>allowed.includes(req.staff.role)?next():res.status(403).json({error:'Insufficient permissions'})}
function validSearch({destination,checkin,checkout,guests}){if(!destination||destination.length>150||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(checkin)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(checkout)||new Date(checkout)<=new Date(checkin)||!Number.isInteger(Number(guests))||Number(guests)<1||Number(guests)>30)return false;return true}
function fill(t,p){return t?.replaceAll('{destination}',encodeURIComponent(p.destination)).replaceAll('{checkin}',p.checkin).replaceAll('{checkout}',p.checkout).replaceAll('{guests}',p.guests) || null}
app.post('/api/auth/login',loginLimit,async(req,res)=>{const {username,password}=req.body||{};if(typeof username!=='string'||typeof password!=='string')return res.status(400).json({error:'Invalid login'});const r=await db.query('SELECT * FROM staff WHERE username=$1',[username]);const s=r.rows[0];if(!s||!await bcrypt.compare(password,s.password_hash))return res.status(401).json({error:'Invalid username or password'});const temp=jwt.sign({staffId:s.id},JWT_SECRET,{expiresIn:'5m'});pending.set(temp,s.id);res.json({tempToken:temp,needs2fa:true})});
app.post('/api/auth/verify-2fa',loginLimit,async(req,res)=>{const {tempToken,code}=req.body||{};const id=pending.get(tempToken);if(!id)return res.status(401).json({error:'Login expired, start again'});const r=await db.query('SELECT id,username,role,totp_secret FROM staff WHERE id=$1',[id]);const s=r.rows[0];if(!s||!speakeasy.totp.verify({secret:s.totp_secret,encoding:'base32',token:String(code),window:1}))return res.status(401).json({error:'Invalid authenticator code'});pending.delete(tempToken);const session=jwt.sign({staffId:s.id,username:s.username,role:s.role},JWT_SECRET,{expiresIn:'8h'});res.cookie('session',session,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:8*3600*1000});res.json({ok:true,username:s.username,role:s.role})});
app.post('/api/auth/logout',auth,(req,res)=>{res.clearCookie('session',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax'});res.json({ok:true})});
app.get('/api/auth/me',auth,(req,res)=>res.json({username:req.staff.username,role:req.staff.role}));
app.get('/api/sources',auth,async(req,res)=>{const r=await db.query('SELECT id,name,login_url,deep_link_template,site_username FROM sources ORDER BY name');res.json(r.rows)});
app.get('/api/admin/sources',auth,roles('SUPER_ADMIN','ADMIN'),async(req,res)=>{const r=await db.query('SELECT id,name,login_url,deep_link_template,site_username,site_password_enc FROM sources ORDER BY name');res.json(r.rows.map(x=>({...x,hasPassword:!!x.site_password_enc,site_password_enc:undefined})))});
app.post('/api/sources',auth,roles('SUPER_ADMIN','ADMIN'),async(req,res)=>{const {name,login_url,deep_link_template,site_username,site_password}=req.body||{};if(!name||!login_url)return res.status(400).json({error:'Name and login URL are required'});try{new URL(login_url)}catch{return res.status(400).json({error:'Invalid login URL'})}const r=await db.query('INSERT INTO sources(name,login_url,deep_link_template,site_username,site_password_enc) VALUES($1,$2,$3,$4,$5) RETURNING id',[name.slice(0,120),login_url,deep_link_template||'',site_username||'',encrypt(site_password||'')]);res.json({id:r.rows[0].id})});
app.delete('/api/sources/:id',auth,roles('SUPER_ADMIN','ADMIN'),async(req,res)=>{await db.query('DELETE FROM sources WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.post('/api/search',auth,async(req,res)=>{const {destination,checkin,checkout,guests}=req.body||{};if(!validSearch({destination,checkin,checkout,guests}))return res.status(400).json({error:'Check destination, dates and guests'});const r=await db.query('INSERT INTO searches(staff_id,destination,checkin,checkout,guests) VALUES($1,$2,$3,$4,$5) RETURNING id',[req.staff.staffId,destination.trim(),checkin,checkout,Number(guests)]);const s=await db.query('SELECT id,name,login_url,deep_link_template FROM sources ORDER BY name');res.json({searchId:r.rows[0].id,links:s.rows.map(x=>({sourceId:x.id,name:x.name,url:fill(x.deep_link_template,{destination,checkin,checkout,guests})||x.login_url}))})});
app.get('/api/history',auth,async(req,res)=>{const isAdmin=['SUPER_ADMIN','ADMIN','MANAGER'].includes(req.staff.role);const q=isAdmin?'SELECT searches.*,staff.username FROM searches JOIN staff ON staff.id=searches.staff_id ORDER BY created_at DESC LIMIT 100':'SELECT searches.*,staff.username FROM searches JOIN staff ON staff.id=searches.staff_id WHERE staff_id=$1 ORDER BY created_at DESC LIMIT 100';const r=await db.query(q,isAdmin?[]:[req.staff.staffId]);res.json(r.rows)});
async function canSeeSearch(id,staff){const r=await db.query('SELECT staff_id FROM searches WHERE id=$1',[id]);return r.rows[0]&& (Number(r.rows[0].staff_id)===Number(staff.staffId)||['SUPER_ADMIN','ADMIN','MANAGER'].includes(staff.role))}
app.get('/api/comparisons/:searchId',auth,async(req,res)=>{if(!await canSeeSearch(req.params.searchId,req.staff))return res.status(403).json({error:'Not authorized'});const r=await db.query('SELECT c.*,s.name source_name FROM comparisons c JOIN sources s ON s.id=c.source_id WHERE search_id=$1 ORDER BY price ASC',[req.params.searchId]);res.json(r.rows)});
app.post('/api/comparisons',auth,async(req,res)=>{const {search_id,source_id,price,room_type,notes}=req.body||{};if(!await canSeeSearch(search_id,req.staff))return res.status(403).json({error:'Not authorized'});const n=Number(price);if(!Number.isFinite(n)||n<0||n>100000000)return res.status(400).json({error:'Invalid price'});const r=await db.query('INSERT INTO comparisons(search_id,source_id,price,room_type,notes) VALUES($1,$2,$3,$4,$5) RETURNING id',[search_id,source_id,n,String(room_type||'').slice(0,200),String(notes||'').slice(0,500)]);res.json({id:r.rows[0].id})});
app.delete('/api/comparisons/:id',auth,async(req,res)=>{const r=await db.query('SELECT search_id FROM comparisons WHERE id=$1',[req.params.id]);if(!r.rows[0]||!await canSeeSearch(r.rows[0].search_id,req.staff))return res.status(403).json({error:'Not authorized'});await db.query('DELETE FROM comparisons WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.get('/health',async(req,res)=>{try{await db.query('SELECT 1');res.json({ok:true})}catch(e){res.status(503).json({ok:false})}});

// Netlify needs the Express app exported to the Function wrapper. Start a real
// HTTP listener only for local/non-Netlify execution.
const initPromise=db.init();
initPromise.catch(e=>console.error(e));
if(!process.env.NETLIFY){
  initPromise.then(()=>{const port=process.env.PORT||3000;app.listen(port,'0.0.0.0',()=>console.log(`Hotel portal listening on ${port}`))}).catch(()=>process.exit(1));
}
module.exports={app,initPromise};
