require('dotenv').config();
const express=require('express'),cookieParser=require('cookie-parser'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),speakeasy=require('speakeasy'),helmet=require('helmet'),rateLimit=require('express-rate-limit');
const db=require('./db');const {encrypt}=require('./crypto-util');const connectors=require('./connectors');
const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(helmet({crossOriginResourcePolicy:false}));app.use(express.json({limit:'100kb'}));app.use(cookieParser());app.use(express.static('public'));
const JWT_SECRET=process.env.JWT_SECRET;if(!JWT_SECRET||JWT_SECRET.length<32)throw new Error('JWT_SECRET must be at least 32 characters');
const pending=new Map();const loginLimit=rateLimit({windowMs:15*60*1000,max:10,standardHeaders:true,legacyHeaders:false});
function auth(req,res,next){const t=req.cookies.session;if(!t)return res.status(401).json({error:'Not logged in'});try{req.staff=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:'Session expired, please log in again'})}}
function roles(...allowed){return(req,res,next)=>allowed.includes(req.staff.role)?next():res.status(403).json({error:'Insufficient permissions'})}
const BOARDS=['ROOM_ONLY','BED_AND_BREAKFAST','HALF_BOARD','FULL_BOARD','ALL_INCLUSIVE'];
function validSearch({destination,checkin,checkout,guests,rooms,board}){return !!destination&&destination.length<=150&&/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(checkin)&&/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(checkout)&&new Date(checkout)>new Date(checkin)&&Number.isInteger(Number(guests))&&Number(guests)>=1&&Number(guests)<=30&&Number.isInteger(Number(rooms))&&Number(rooms)>=1&&Number(rooms)<=20&&BOARDS.includes(board)}
function fill(t,p){return t?.replaceAll('{destination}',encodeURIComponent(p.destination)).replaceAll('{checkin}',p.checkin).replaceAll('{checkout}',p.checkout).replaceAll('{guests}',p.guests).replaceAll('{rooms}',p.rooms).replaceAll('{board}',p.board)||null}
app.post('/api/auth/login',loginLimit,async(req,res)=>{try{const{username,password}=req.body||{};if(typeof username!=='string'||typeof password!=='string')return res.status(400).json({error:'Invalid login'});const r=await db.query('SELECT * FROM staff WHERE username=$1',[username]);const s=r.rows[0];if(!s||!await bcrypt.compare(password,s.password_hash))return res.status(401).json({error:'Invalid username or password'});const temp=jwt.sign({staffId:s.id},JWT_SECRET,{expiresIn:'5m'});pending.set(temp,s.id);res.json({tempToken:temp,needs2fa:true})}catch(e){console.error(e);res.status(500).json({error:'Login service error'})}});
app.post('/api/auth/verify-2fa',loginLimit,async(req,res)=>{try{const{tempToken,code}=req.body||{};const id=pending.get(tempToken);if(!id)return res.status(401).json({error:'Login expired, start again'});const r=await db.query('SELECT id,username,role,totp_secret FROM staff WHERE id=$1',[id]);const s=r.rows[0];if(!s||!speakeasy.totp.verify({secret:s.totp_secret,encoding:'base32',token:String(code),window:1}))return res.status(401).json({error:'Invalid authenticator code'});pending.delete(tempToken);const session=jwt.sign({staffId:s.id,username:s.username,role:s.role},JWT_SECRET,{expiresIn:'8h'});res.cookie('session',session,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:8*3600*1000});res.json({ok:true,username:s.username,role:s.role})}catch(e){console.error(e);res.status(500).json({error:'2FA service error'})}});
app.post('/api/auth/logout',auth,(req,res)=>{res.clearCookie('session',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax'});res.json({ok:true})});
app.get('/api/auth/me',auth,(req,res)=>res.json({username:req.staff.username,role:req.staff.role}));
app.get('/api/sources',auth,async(req,res)=>{const r=await db.query('SELECT id,name,login_url,deep_link_template,site_username FROM sources ORDER BY name');res.json(r.rows)});
app.get('/api/connectors',auth,(req,res)=>res.json(connectors.configuredConnectors()));
app.get('/api/admin/sources',auth,roles('SUPER_ADMIN','ADMIN'),async(req,res)=>{const r=await db.query('SELECT id,name,login_url,deep_link_template,site_username,site_password_enc FROM sources ORDER BY name');res.json(r.rows.map(x=>({...x,hasPassword:!!x.site_password_enc,site_password_enc:undefined})))});
app.post('/api/sources',auth,roles('SUPER_ADMIN','ADMIN'),async(req,res)=>{try{const{name,login_url,deep_link_template,site_username,site_password}=req.body||{};if(!name||!login_url)return res.status(400).json({error:'Name and login URL are required'});try{new URL(login_url)}catch{return res.status(400).json({error:'Invalid login URL'})}const r=await db.query('INSERT INTO sources(name,login_url,deep_link_template,site_username,site_password_enc) VALUES($1,$2,$3,$4,$5) RETURNING id',[name.slice(0,120),login_url,deep_link_template||'',site_username||'',encrypt(site_password||'')]);res.json({id:r.rows[0].id})}catch(e){console.error(e);res.status(500).json({error:'Could not save source. Please check the source details and try again.'})}});
app.delete('/api/sources/:id',auth,roles('SUPER_ADMIN','ADMIN'),async(req,res)=>{await db.query('DELETE FROM sources WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.post('/api/search',auth,async(req,res)=>{try{const{destination,checkin,checkout,guests,rooms=1,board='ROOM_ONLY'}=req.body||{};if(!validSearch({destination,checkin,checkout,guests,rooms,board}))return res.status(400).json({error:'Check destination, dates, guests, rooms and board'});const r=await db.query('INSERT INTO searches(staff_id,destination,checkin,checkout,guests,rooms,board) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[req.staff.staffId,destination.trim(),checkin,checkout,Number(guests),Number(rooms),board]);const s=await db.query('SELECT id,name,login_url,deep_link_template FROM sources ORDER BY name');const connectorResult=await connectors.searchAll({destination:destination.trim(),checkin,checkout,guests:Number(guests),rooms:Number(rooms),board});res.json({searchId:r.rows[0].id,results:connectorResult.results,connectorStatuses:connectorResult.statuses,links:s.rows.map(x=>({sourceId:x.id,name:x.name,url:fill(x.deep_link_template,{destination,checkin,checkout,guests,rooms,board})||x.login_url}))})}catch(e){console.error(e);res.status(500).json({error:'Search could not be completed'})}});
app.get('/api/history',auth,async(req,res)=>{const isAdmin=['SUPER_ADMIN','ADMIN','MANAGER'].includes(req.staff.role);const q=isAdmin?'SELECT searches.*,staff.username FROM searches JOIN staff ON staff.id=searches.staff_id ORDER BY created_at DESC LIMIT 100':'SELECT searches.*,staff.username FROM searches JOIN staff ON staff.id=searches.staff_id WHERE staff_id=$1 ORDER BY created_at DESC LIMIT 100';const r=await db.query(q,isAdmin?[]:[req.staff.staffId]);res.json(r.rows)});
app.get('/api/comparisons/:searchId',auth,async(req,res)=>res.json([]));
app.delete('/api/comparisons/:id',auth,async(req,res)=>res.json({ok:true}));
app.get('/health',async(req,res)=>{try{await db.query('SELECT 1');res.json({ok:true})}catch(e){console.error(e);res.status(503).json({ok:false})}});
const initPromise=db.init();initPromise.catch(e=>console.error(e));
if(!process.env.NETLIFY){initPromise.then(()=>{const port=process.env.PORT||3000;app.listen(port,'0.0.0.0',()=>console.log(`Hotel portal listening on ${port}`))}).catch(()=>process.exit(1))}
module.exports={app,initPromise};
