const { chromium } = require('playwright');
const { decrypt } = require('../crypto-util');
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const PRICE_RE=/(?:AED|SAR|USD|EUR|GBP|PKR|US\$|\$)\s*[0-9][0-9,]*(?:\.[0-9]{1,2})?|\b[0-9]{2,6}\.[0-9]{2}\b/i;
const PRICE_GLOBAL=/(?:AED|SAR|USD|EUR|GBP|PKR|US\$|\$)\s*[0-9][0-9,]*(?:\.[0-9]{1,2})?|\b[0-9]{2,6}\.[0-9]{2}\b/gi;
const LOGIN_FRAME='https://iolglobalb2bcloudssl.iolcloud.com/login.aspx?SourceXid=MTE3NTNTM=';
const frames=p=>p.frames(); const pages=c=>c.pages();
async function text(f){return clean(await f.locator('body').innerText({timeout:10000}).catch(()=>''));}
async function blocked(p){for(const f of frames(p))if(/captcha|verify you are human|access denied|unusual traffic|security check/i.test(await text(f)))throw new Error('Supplier presented a security verification step; automated bypass is not supported');}
async function loggedIn(p){let t='';for(const f of frames(p))t+=' '+await text(f);return /welcome\b|\blogout\b/i.test(t);}
async function findFrame(p,s){for(const f of frames(p)){try{if(await f.locator(s).count())return f;}catch{}}return null;}
async function login(p,source,password,cfg){let f=null,end=Date.now()+(Number(cfg.login_frame_timeout_ms)||45000);while(!f&&Date.now()<end){f=await findFrame(p,'#tbUserName');if(!f)f=frames(p).find(x=>/login\.aspx/i.test(x.url()))||null;if(!f)await p.waitForTimeout(500);}if(!f){try{await p.goto(cfg.login_frame_url||LOGIN_FRAME,{waitUntil:'commit',timeout:20000});await p.waitForTimeout(2000);}catch{}f=await findFrame(p,'#tbUserName');}if(!f){if(await loggedIn(p))return;throw new Error('Hadaf login iframe/fields could not be detected');}await f.locator('#tbUserName').fill(String(source.site_username||''));await f.locator('#tbPassword').fill(String(password||''));const terms=f.locator('#chkTermCondn').first();if(await terms.count().catch(()=>0)&&!(await terms.isChecked().catch(()=>false)))await terms.check().catch(()=>{});await f.locator('#btnLogin1').click({timeout:10000});await p.waitForTimeout(Number(cfg.post_login_wait_ms)||7000);await blocked(p);if(!await loggedIn(p))throw new Error('Hadaf login was submitted but the portal did not show a logged-in state');}
async function openHadaf(source){const cfg=source.browser_config||{};if(!source.login_url||!source.site_username||!source.site_password_enc)return{configured:false,live:false,error:'Hadaf credentials are not configured'};let password;try{password=decrypt(source.site_password_enc);}catch(e){return{configured:true,live:false,error:`Credential decryption failed: ${e.message}`};}let browser,context,stage='launch';try{browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage();p.setDefaultTimeout(Number(cfg.timeout_ms)||15000);stage='open portal';await p.goto(source.login_url,{waitUntil:'commit',timeout:60000});await p.waitForTimeout(Number(cfg.initial_wait_ms)||3000);await blocked(p);stage='login';await login(p,source,password,cfg);return{configured:true,live:true,page:p,context,browser};}catch(e){if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});return{configured:true,live:false,error:e.name==='TimeoutError'?`Hadaf browser timed out during ${stage}`:e.message};}}
async function healthHadafSource(source){const r=await openHadaf(source);if(r.context)await r.context.close().catch(()=>{});if(r.browser)await r.browser.close().catch(()=>{});return{configured:r.configured,live:r.live,error:r.error||null};}
function date(v){const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(v||'');}
async function findSearchTarget(context,cfg){const end=Date.now()+(Number(cfg.search_page_timeout_ms)||45000);while(Date.now()<end){for(const p of pages(context)){for(const f of frames(p)){const t=await text(f);if(/Hotel Search/i.test(t)&&/Destination City\s*\/\s*Zone/i.test(t)&&await f.locator('input:visible').count().catch(()=>0)>0)return{page:p,frame:f};}}await new Promise(r=>setTimeout(r,500));}return null;}
async function controlNearLabel(f,label,tag){const controls=f.locator(`${tag}:visible`);const n=await controls.count().catch(()=>0);for(let i=0;i<n;i++){const x=controls.nth(i);const hit=await x.evaluate((el,label)=>{let n=el;for(let i=0;i<6&&n;i++,n=n.parentElement){const t=(n.innerText||'').replace(/\s+/g,' ').trim();if(t.includes(label))return true;}return false;},label).catch(()=>false);if(hit)return x;}return null;}
async function firstVisible(f,selectors){for(const s of selectors.filter(Boolean)){try{const x=f.locator(s).first();if(await x.count()&&await x.isVisible())return x;}catch{}}return null;}
async function findLabeled(f,label,tag,selectors){return await controlNearLabel(f,label,tag)||await firstVisible(f,selectors);}
async function searchPortal(context,s,cfg){const target=await findSearchTarget(context,cfg);if(!target)throw new Error('Hadaf hotel search form could not be detected');const f=target.frame;const d=await findLabeled(f,'Destination City / Zone','input',[cfg.destination_selector,'input[name*="destination" i]','input[id*="destination" i]','input[name*="city" i]','input[id*="city" i]']);if(!d)throw new Error('Hadaf destination field could not be detected');await d.fill(String(s.destination));await d.press('Tab').catch(()=>{});await target.page.waitForTimeout(700);const ci=await findLabeled(f,'Check-in Date','input',[cfg.checkin_selector,'input[name*="checkin" i]','input[id*="checkin" i]','input[name*="arrival" i]']);const co=await findLabeled(f,'Check-out Date','input',[cfg.checkout_selector,'input[name*="checkout" i]','input[id*="checkout" i]','input[name*="departure" i]']);if(!ci||!co)throw new Error('Hadaf check-in/check-out fields could not be detected');await ci.fill(date(s.checkin));await ci.press('Tab').catch(()=>{});await co.fill(date(s.checkout));await co.press('Tab').catch(()=>{});const rooms=await findLabeled(f,'Room/s','select',[cfg.rooms_selector,'select[name*="room" i]','select[id*="room" i]']);if(rooms)await rooms.selectOption({label:String(s.rooms||1)}).catch(()=>{});const adults=await findLabeled(f,'Room 1 Adults','select',[cfg.guests_selector,'select[name*="adult" i]','select[id*="adult" i]']);if(adults)await adults.selectOption({label:String(s.guests||2)}).catch(()=>{});const btn=await findLabeled(f,'Search','input',[cfg.search_button_selector,'input[value*="search" i]']);if(btn){await btn.click({timeout:10000});return;}const b=await findLabeled(f,'Search','button',['button:has-text("Search")','a:has-text("Search")']);if(!b)throw new Error('Hadaf search button could not be detected');await b.click({timeout:10000});}
function parseRate(t,def='AED'){const m=clean(t).match(PRICE_RE);if(!m)return null;const n=m[0].match(/[0-9][0-9,]*(?:\.[0-9]{1,2})?/);const price=Number(n?.[0]?.replace(/,/g,''));if(!Number.isFinite(price)||price<=0)return null;const c=(m[0].match(/AED|SAR|USD|EUR|GBP|PKR|US\$|\$/i)||[def])[0];return{price,currency:clean(c),room:clean((t.match(/(?:Triple|Twin|Double|Single|Quadruple|Family|Deluxe|Standard|Superior|King|Queen|Suite|Apartment|Villa)[^|]*?(?:Room|Suite|Bed|Only|Included)?/i)||[''])[0]),board:clean((t.match(/Room Only|Breakfast Included|Bed and Breakfast|Half Board|Full Board|All Inclusive/i)||[''])[0]),cancellation:clean((t.match(/Non[- ]?refundable|Free Cancellation|Refundable/i)||[''])[0]),availability:clean((t.match(/Available|On Request|Sold Out|Not Available/i)||['Available'])[0]),raw:clean(t)};}
function hotelLike(t){return t.length>=4&&t.length<=180&&!PRICE_RE.test(t)&&/hotel|resort|suites|residence|makkah|madinah|riyadh|jeddah/i.test(t);}
async function extractFrame(f,cfg){let body='';try{body=await f.locator('body').evaluate(el=>el.innerText||el.textContent||'').catch(()=> '');}catch{}const flat=clean(body);const lines=String(body).split(/\r?\n/).map(clean).filter(Boolean);const windows=[];let m;while((m=PRICE_GLOBAL.exec(flat))!==null){const start=Math.max(0,m.index-350),end=Math.min(flat.length,m.index+m[0].length+500);windows.push(flat.slice(start,end));}const out=[];for(const w of windows){const r=parseRate(w,cfg.default_currency||'AED');if(r)out.push({hotel:'',...r});}for(let i=0;i<lines.length;i++){if(!PRICE_RE.test(lines[i]))continue;const r=parseRate(lines.slice(Math.max(0,i-12),Math.min(lines.length,i+15)).join(' | '),cfg.default_currency||'AED');if(r)out.push({hotel:'',...r});}if(!out.length){const nodes=await f.locator('body *').evaluateAll((els)=>els.map(e=>{const r=e.getBoundingClientRect(),t=(e.innerText||e.textContent||'').replace(/\s+/g,' ').trim();return{t,w:r.width,h:r.height};}).filter(x=>x.w>0&&x.h>0&&x.t.length>0&&x.t.length<1000&&/(?:AED|SAR|USD|EUR|GBP|PKR|US\$|\$)\s*[0-9]|\b[0-9]{2,6}\.[0-9]{2}\b/i.test(x.t)).map(x=>x.t));for(const raw of nodes){const r=parseRate(raw,cfg.default_currency||'AED');if(r)out.push({hotel:'',...r});}}for(const r of out){let idx=lines.findIndex(x=>x.includes(r.raw.slice(0,30)));if(idx<0)idx=lines.findIndex(x=>PRICE_RE.test(x)&&x.includes(String(r.price)));for(let j=Math.max(0,idx-40);j>=0;j--)if(hotelLike(lines[j])){r.hotel=lines[j];break;}}return out;}
async function extract(context,cfg){const all=[];for(const p of pages(context))for(const f of frames(p))all.push(...await extractFrame(f,cfg));const seen=new Set();return all.filter(r=>r.price>0).filter(r=>{const k=[r.hotel,r.room,r.board,r.price,r.currency,r.cancellation,r.raw].join('|');if(seen.has(k))return false;seen.add(k);return true;}).slice(0,Number(cfg.max_results)||500);}
async function hasResults(context){for(const p of pages(context))for(const f of frames(p))if(/Hotels In|Room Type|Dynamic Inventory|Non-refundable/i.test(await text(f)))return true;return false;}
async function searchHadafSource(source,search){const cfg=source.browser_config||{};if(!source.login_url||!source.site_username||!source.site_password_enc)return{configured:false,results:[],error:null};let password;try{password=decrypt(source.site_password_enc);}catch(e){return{configured:true,results:[],error:`Credential decryption failed: ${e.message}`};}let browser,context,stage='launch';try{browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1000}});const loginPage=await context.newPage();loginPage.setDefaultTimeout(Number(cfg.timeout_ms)||15000);stage='open portal';await loginPage.goto(source.login_url,{waitUntil:'commit',timeout:60000});await loginPage.waitForTimeout(Number(cfg.initial_wait_ms)||3000);await blocked(loginPage);stage='login';await login(loginPage,source,password,cfg);stage='search form';await searchPortal(context,search,cfg);stage='results';const end=Date.now()+(Number(cfg.results_wait_ms)||45000);while(Date.now()<end&&!(await hasResults(context)))await new Promise(r=>setTimeout(r,500));for(const p of pages(context))await blocked(p);stage='extract';const results=(await extract(context,cfg)).map((r,i)=>({id:`${source.id}-${i}`,supplier:source.name,hotel:r.hotel||'Hotel',room:r.room||'',view:r.view||'',board:r.board||search.board||'',cancellation:r.cancellation||'',price:Number(r.price),currency:r.currency||cfg.default_currency||'AED',availability:r.availability||'Available',raw:r.raw||r,image:'',bookingUrl:''}));if(!results.length)return{configured:true,results:[],error:'Hadaf login/search completed but no priced rates were extracted'};return{configured:true,results,error:null};}catch(e){return{configured:true,results:[],error:e.name==='TimeoutError'?`Hadaf browser timed out during ${stage}`:e.message};}finally{if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});}}
module.exports={searchHadafSource,healthHadafSource};
