const { chromium } = require('playwright');
const { decrypt } = require('../crypto-util');
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const PRICE_RE=/(?:AED|SAR|USD|EUR|GBP|PKR|US\$|\$)\s*[0-9][0-9,]*(?:\.[0-9]{1,2})?|\b[0-9]{2,6}\.[0-9]{2}\b/i;
const PRICE_GLOBAL=/(?:AED|SAR|USD|EUR|GBP|PKR|US\$|\$)\s*[0-9][0-9,]*(?:\.[0-9]{1,2})?|\b[0-9]{2,6}\.[0-9]{2}\b/gi;
const LOGIN_FRAME='https://iolglobalb2bcloudssl.iolcloud.com/login.aspx?SourceXid=MTE3NTNTM=';
const frames=p=>p.frames();const pages=c=>c.pages();
async function text(f){return clean(await f.locator('body').innerText().catch(()=>''));}
async function blocked(p){for(const f of frames(p))if(/captcha|verify you are human|access denied|unusual traffic|security check/i.test(await text(f)))throw new Error('Supplier presented a security verification step; automated bypass is not supported');}
async function loggedIn(p){let t='';for(const f of frames(p))t+=' '+await text(f);return /welcome\b|\blogout\b/i.test(t);}
async function findFrame(p,s){for(const f of frames(p)){try{if(await f.locator(s).count())return f;}catch{}}return null;}
async function login(p,source,password,cfg){let f=null,end=Date.now()+(Number(cfg.login_frame_timeout_ms)||45000);while(!f&&Date.now()<end){f=await findFrame(p,'#tbUserName');if(!f)f=frames(p).find(x=>/login\.aspx/i.test(x.url()))||null;if(!f)await p.waitForTimeout(500);}if(!f){try{await p.goto(cfg.login_frame_url||LOGIN_FRAME,{waitUntil:'commit',timeout:20000});await p.waitForTimeout(2000);}catch{}f=await findFrame(p,'#tbUserName');}if(!f){if(await loggedIn(p))return;throw new Error('Hadaf login iframe/fields could not be detected');}await f.locator('#tbUserName').fill(String(source.site_username||''));await f.locator('#tbPassword').fill(String(password||''));const terms=f.locator('#chkTermCondn').first();if(await terms.count().catch(()=>0)&&!(await terms.isChecked().catch(()=>false)))await terms.check().catch(()=>{});await f.locator('#btnLogin1').click({timeout:10000});await p.waitForTimeout(Number(cfg.post_login_wait_ms)||7000);await blocked(p);if(!await loggedIn(p))throw new Error('Hadaf login was submitted but the portal did not show a logged-in state');}
async function openHadaf(source){const cfg=source.browser_config||{};if(!source.login_url||!source.site_username||!source.site_password_enc)return{configured:false,live:false,error:'Hadaf credentials are not configured'};let password;try{password=decrypt(source.site_password_enc)}catch(e){return{configured:true,live:false,error:`Credential decryption failed: ${e.message}`}}let browser,context,stage='launch';try{browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage();p.setDefaultTimeout(Number(cfg.timeout_ms)||15000);stage='open portal';await p.goto(source.login_url,{waitUntil:'commit',timeout:60000});await p.waitForTimeout(Number(cfg.initial_wait_ms)||3000);await blocked(p);stage='login';await login(p,source,password,cfg);return{configured:true,live:true,page:p,context,browser}}catch(e){if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});return{configured:true,live:false,error:e.name==='TimeoutError'?`Hadaf browser timed out during ${stage}`:e.message}}}
async function healthHadafSource(source){const r=await openHadaf(source);if(r.context)await r.context.close().catch(()=>{});if(r.browser)await r.browser.close().catch(()=>{});return{configured:r.configured,live:r.live,error:r.error||null}}
function date(v){const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(v||'');}
async function findSearchTarget(context,cfg){const end=Date.now()+(Number(cfg.search_page_timeout_ms)||45000);while(Date.now()<end){for(const p of pages(context))for(const f of frames(p)){const t=await text(f);if(/Hotel Search/i.test(t)&&/Destination City\s*\/\s*Zone/i.test(t)&&await f.locator('input:visible').count().catch(()=>0)>0)return{page:p,frame:f}}await new Promise(r=>setTimeout(r,500))}return null}
async function controlNearLabel(f,label,tag){const controls=f.locator(`${tag}:visible`);const n=await controls.count().catch(()=>0);for(let i=0;i<n;i++){const x=controls.nth(i);const hit=await x.evaluate((el,label)=>{let n=el;for(let i=0;i<6&&n;i++,n=n.parentElement){const t=(n.innerText||'').replace(/\s+/g,' ').trim();if(t.includes(label))return true}return false},label).catch(()=>false);if(hit)return x}return null}
async function firstVisible(f,selectors){for(const s of selectors.filter(Boolean)){try{const x=f.locator(s).first();if(await x.count()&&await x.isVisible())return x}catch{}}return null}
async function findLabeled(f,label,tag,selectors){return await controlNearLabel(f,label,tag)||await firstVisible(f,selectors)}
async function chooseDestination(f,value){const wanted=clean(value).toLowerCase();if(!wanted)return;await new Promise(r=>setTimeout(r,1000));const candidates=await f.locator('li:visible,option:visible,[role="option"]:visible,[role="listbox"] *:visible').evaluateAll((els,wanted)=>els.map(e=>({text:(e.innerText||e.textContent||'').replace(/\s+/g,' ').trim(),html:e.outerHTML})).filter(x=>x.text&&x.text.toLowerCase().includes(wanted)).slice(0,10),wanted).catch(()=>[]);if(!candidates.length)return;const exact=f.locator('li:visible,[role="option"]:visible').filter({hasText:new RegExp(wanted.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i')}).first();if(await exact.count().catch(()=>0))await exact.click().catch(()=>{});}
async function searchPortal(context,s,cfg){const target=await findSearchTarget(context,cfg);if(!target)throw new Error('Hadaf hotel search form could not be detected');const f=target.frame;const d=await findLabeled(f,'Destination City / Zone','input',[cfg.destination_selector,'input[name*="destination" i]','input[id*="destination" i]','input[name*="city" i]','input[id*="city" i]']);if(!d)throw new Error('Hadaf destination field could not be detected');await d.fill(String(s.destination));await d.press('ArrowDown').catch(()=>{});await chooseDestination(f,s.destination);await d.press('Tab').catch(()=>{});await target.page.waitForTimeout(700);const ci=await findLabeled(f,'Check-in Date','input',[cfg.checkin_selector,'input[name*="checkin" i]','input[id*="checkin" i]','input[name*="arrival" i]']);const co=await findLabeled(f,'Check-out Date','input',[cfg.checkout_selector,'input[name*="checkout" i]','input[id*="checkout" i]','input[name*="departure" i]']);if(!ci||!co)throw new Error('Hadaf check-in/check-out fields could not be detected');await ci.fill(date(s.checkin));await ci.press('Tab').catch(()=>{});await co.fill(date(s.checkout));await co.press('Tab').catch(()=>{});const rooms=await findLabeled(f,'Room/s','select',[cfg.rooms_selector,'select[name*="room" i]','select[id*="room" i]']);if(rooms)await rooms.selectOption({label:String(s.rooms||1)}).catch(()=>{});const adults=await findLabeled(f,'Room 1 Adults','select',[cfg.guests_selector,'select[name*="adult" i]','select[id*="adult" i]']);if(adults)await adults.selectOption({label:String(s.guests||2)}).catch(()=>{});const btn=await findLabeled(f,'Search','input',[cfg.search_button_selector,'input[value*="search" i]']);if(btn){await btn.click({timeout:10000});return}const b=await findLabeled(f,'Search','button',['button:has-text("Search")','a:has-text("Search")']);if(!b)throw new Error('Hadaf search button could not be detected');await b.click({timeout:10000})}
function parseRate(t,def='AED'){const m=clean(t).match(PRICE_RE);if(!m)return null;const n=m[0].match(/[0-9][0-9,]*(?:\.[0-9]{1,2})?/);const price=Number(n?.[0]?.replace(/,/g,''));if(!Number.isFinite(price)||price<=0)return null;const c=(m[0].match(/AED|SAR|USD|EUR|GBP|PKR|US\$|\$/i)||[def])[0];return{price,currency:clean(c),room:clean((t.match(/(?:Triple|Twin|Double|Single|Quadruple|Family|Deluxe|Standard|Superior|King|Queen|Suite|Apartment|Villa)[^|]*?(?:Room|Suite|Bed|Only|Included)?/i)||[''])[0]),board:clean((t.match(/Room Only|Breakfast Included|Bed and Breakfast|Half Board|Full Board|All Inclusive/i)||[''])[0]),cancellation:clean((t.match(/Non[- ]?refundable|Free Cancellation|Refundable/i)||[''])[0]),availability:clean((t.match(/Available|On Request|Sold Out|Not Available/i)||['Available'])[0]),raw:clean(t)}}
function hotelLike(t){return t.length>=4&&t.length<=180&&!PRICE_RE.test(t)&&/hotel|resort|suites|residence|makkah|madinah|riyadh|jeddah/i.test(t)}
async function extractFrame(f,cfg){const rawText=await f.locator('body').evaluate(b=>`${b.innerText||''}\n${b.textContent||''}`).catch(()=>f.locator('body').innerText().catch(()=>''));const lines=String(rawText||'').split(/\r?\n/).map(clean).filter(Boolean);const full=lines.join(' | ');const matches=full.match(PRICE_GLOBAL)||[];const out=[];for(const token of matches){let idx=lines.findIndex(x=>x.includes(token));let context=lines.slice(Math.max(0,idx-12),Math.min(lines.length,idx+13)).join(' | ');const r=parseRate(context,cfg.default_currency||'AED');if(r)out.push({hotel:'',...r})}const elementTexts=await f.locator('body *').evaluateAll((els)=>els.map(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0?(e.innerText||e.textContent||''):''}).filter(Boolean).slice(0,5000)).catch(()=>[]);for(const raw of elementTexts){if(!PRICE_RE.test(raw))continue;const r=parseRate(raw,cfg.default_currency||'AED');if(r)out.push({hotel:'',...r})}for(const r of out){let idx=lines.findIndex(x=>x.includes(String(r.price))&&PRICE_RE.test(x));if(idx<0)continue;for(let j=Math.max(0,idx-30);j>=0;j--)if(hotelLike(lines[j])){r.hotel=lines[j];break}}return out}
async function extract(context,cfg){const all=[];for(const p of pages(context))for(const f of frames(p))all.push(...await extractFrame(f,cfg));const seen=new Set();return all.filter(r=>r.price>0).filter(r=>{const k=[r.hotel,r.room,r.board,r.price,r.currency,r.cancellation,r.raw].join('|');if(seen.has(k))return false;seen.add(k);return true}).slice(0,Number(cfg.max_results)||500)}
async function hasResults(context){for(const p of pages(context))for(const f of frames(p))if(/Hotels In|Room Type|Dynamic Inventory|Non-refundable/i.test(await text(f)))return true;return false}
async function diagnostic(context){const out=[];for(const p of pages(context))for(const f of frames(p)){const t=await text(f);if(t)out.push(`${f.url()} :: ${t.slice(0,900)}`)}return out.join(' || ').slice(0,5000)}
async function searchHadafSource(source,search){const cfg=source.browser_config||{};if(!source.login_url||!source.site_username||!source.site_password_enc)return{configured:false,results:[],error:null};let password;try{password=decrypt(source.site_password_enc)}catch(e){return{configured:true,results:[],error:`Credential decryption failed: ${e.message}`}}let browser,context,stage='launch';try{browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1000}});const loginPage=await context.newPage();loginPage.setDefaultTimeout(Number(cfg.timeout_ms)||15000);stage='open portal';await loginPage.goto(source.login_url,{waitUntil:'commit',timeout:60000});await loginPage.waitForTimeout(Number(cfg.initial_wait_ms)||3000);await blocked(loginPage);stage='login';await login(loginPage,source,password,cfg);stage='search form';await searchPortal(context,search,cfg);stage='results';const end=Date.now()+(Number(cfg.results_wait_ms)||90000);while(Date.now()<end&&!(await hasResults(context)))await new Promise(r=>setTimeout(r,500));for(const p of pages(context))await blocked(p);stage='extract';const results=(await extract(context,cfg)).map((r,i)=>({id:`${source.id}-${i}`,supplier:source.name,hotel:r.hotel||'Hotel',room:r.room||'',view:r.view||'',board:r.board||search.board||'ROOM_ONLY',cancellation:r.cancellation||'',price:Number(r.price),currency:r.currency||cfg.default_currency||'AED',availability:r.availability||'Available',raw:r.raw||r,image:'',bookingUrl:''}));if(!results.length){const d=await diagnostic(context);return{configured:true,results:[],error:`Hadaf search completed but no priced rates were extracted. Browser pages: ${pages(context).length}. ${d||'No readable result-page text was found.'}`}}return{configured:true,results,error:null}}catch(e){return{configured:true,results:[],error:e.name==='TimeoutError'?`Hadaf browser timed out during ${stage}`:e.message}}finally{if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{})}}
module.exports={searchHadafSource,healthHadafSource};