const { chromium } = require('playwright');
const { decrypt } = require('../crypto-util');
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const PRICE_RE=/(?:AED|SAR|USD|EUR|GBP|PKR|US\$|\$)\s*[0-9][0-9,]*(?:\.[0-9]{1,2})?|\b[0-9]{2,6}\.[0-9]{2}\b/i;
const DEFAULT_LOGIN_FRAME_URL='https://iolglobalb2bcloudssl.iolcloud.com/login.aspx?SourceXid=MTE3NTNTM=';
const allFrames=p=>p.frames();
async function visible(f,s){try{const x=f.locator(s).first();if(await x.count()&&await x.isVisible())return x;}catch{}return null;}
async function findVisible(p,ss){for(const f of allFrames(p))for(const s of ss.filter(Boolean)){const x=await visible(f,s);if(x)return x;}return null;}
async function findFrame(p,s){for(const f of allFrames(p)){try{if(await f.locator(s).count())return f;}catch{}}return null;}
async function blocked(p){let t='';for(const f of allFrames(p))t+=' '+clean(await f.locator('body').innerText().catch(()=>''));if(/captcha|verify you are human|access denied|unusual traffic|security check/i.test(t))throw new Error('Supplier presented a security verification step; automated bypass is not supported');}
async function loggedIn(p){let t='';for(const f of allFrames(p))t+=' '+clean(await f.locator('body').innerText().catch(()=>''));return /welcome\b|\blogout\b/i.test(t);}
async function login(p,source,password,cfg){const started=Date.now(),waitMs=Number(cfg.login_frame_timeout_ms)||30000;let f=null;while(!f&&Date.now()-started<waitMs){f=await findFrame(p,'#tbUserName');if(!f){try{if(await p.locator('#tbUserName').count())f=p;}catch{}}if(!f){const iframes=p.locator('iframe');const n=await iframes.count().catch(()=>0);for(let i=0;i<n&&!f;i++){const iframe=iframes.nth(i);try{const cf=iframe.contentFrame();if(cf&&await cf.locator('#tbUserName').count())f=cf;}catch{}}}if(!f)f=allFrames(p).find(x=>/login\.aspx/i.test(x.url()))||null;if(!f)await p.waitForTimeout(500);}if(!f){await p.goto(cfg.login_frame_url||DEFAULT_LOGIN_FRAME_URL,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(1500);f=await findFrame(p,'#tbUserName');try{if(!f&&await p.locator('#tbUserName').count())f=p;}catch{}}if(!f){if(await loggedIn(p))return;throw new Error('Hadaf login iframe/fields could not be detected');}const user=await visible(f,'#tbUserName')||f.locator('#tbUserName').first(),pass=await visible(f,'#tbPassword')||f.locator('#tbPassword').first(),terms=await visible(f,'#chkTermCondn')||f.locator('#chkTermCondn').first(),btn=await visible(f,'#btnLogin1')||f.locator('#btnLogin1').first();try{await user.waitFor({state:'visible',timeout:10000});await pass.waitFor({state:'visible',timeout:10000});await user.fill(String(source.site_username||''));await pass.fill(String(password||''));if(await terms.count().catch(()=>0)&&!(await terms.isChecked().catch(()=>false)))await terms.check().catch(()=>{});await btn.waitFor({state:'visible',timeout:10000});await btn.click({timeout:10000});}catch(e){throw new Error(`Hadaf login controls could not be used: ${e.message}`);}await p.waitForTimeout(Number(cfg.post_login_wait_ms)||5000);await blocked(p);if(!await loggedIn(p))throw new Error('Hadaf login was submitted but the portal did not show a logged-in state');}
async function openHadaf(source){const cfg=source.browser_config||{};if(!source.login_url||!source.site_username||!source.site_password_enc)return{configured:false,live:false,error:'Hadaf credentials are not configured'};let password;try{password=decrypt(source.site_password_enc);}catch(e){return{configured:true,live:false,error:`Credential decryption failed: ${e.message}`};}let browser,context;try{browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage();p.setDefaultTimeout(Number(cfg.timeout_ms)||15000);await p.goto(source.login_url,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(Number(cfg.initial_wait_ms)||2000);await blocked(p);await login(p,source,password,cfg);return{configured:true,live:true,page:p};}catch(e){if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});return{configured:true,live:false,error:e.name==='TimeoutError'?'Hadaf browser timed out':e.message};}}
async function healthHadafSource(source){const r=await openHadaf(source);if(r.page){const c=r.page.context(),b=c.browser();await c.close().catch(()=>{});if(b)await b.close().catch(()=>{});}return{configured:r.configured,live:r.live,error:r.error||null};}
async function inputCandidates(p){const out=[];for(const f of allFrames(p)){const es=f.locator('input:visible,select:visible,textarea:visible'),n=await es.count().catch(()=>0);for(let i=0;i<n;i++){const el=es.nth(i),a=await Promise.all(['type','name','id','placeholder','value'].map(k=>el.getAttribute(k).catch(()=>'')));out.push({el,meta:a.join(' ').toLowerCase()});}}return out;}
async function ranked(p,purpose){let best=null,score=0;for(const x of await inputCandidates(p)){let s=0,m=x.meta;if(purpose==='destination'){if(/destination|city|zone|location|going to/.test(m))s+=100;if(/hotel name|contains/.test(m))s-=30;}if(purpose==='checkin'){if(/check.?in|arrival/.test(m))s+=100;else if(/date/.test(m))s+=10;}if(purpose==='checkout'){if(/check.?out|departure/.test(m))s+=100;else if(/date/.test(m))s+=10;}if(purpose==='guests'&&/adult|guest|travell?er|pax/.test(m))s+=80;if(purpose==='rooms'&&/room/.test(m))s+=80;if(s>score){score=s;best=x.el;}}return best;}
async function fill(p,purpose,value,selectors){const el=await findVisible(p,selectors)||await ranked(p,purpose);if(!el)return false;try{await el.fill(String(value));await el.press('Tab').catch(()=>{});return true;}catch{return false;}}
async function searchPortal(p,s,cfg){if(cfg.search_url_template){await p.goto(String(cfg.search_url_template).replaceAll('{destination}',encodeURIComponent(s.destination)).replaceAll('{checkin}',s.checkin).replaceAll('{checkout}',s.checkout).replaceAll('{guests}',String(s.guests)).replaceAll('{rooms}',String(s.rooms||1)),{waitUntil:'domcontentloaded',timeout:30000});return;}if(!await fill(p,'destination',s.destination,[cfg.destination_selector,'#txtDestination','input[name*="destination" i]','input[id*="destination" i]','input[placeholder*="going to" i]']))throw new Error('Hadaf destination field could not be detected');const ci=await fill(p,'checkin',s.checkin,[cfg.checkin_selector,'input[name*="checkin" i]','input[id*="checkin" i]','input[name*="arrival" i]','input[id*="arrival" i]']),co=await fill(p,'checkout',s.checkout,[cfg.checkout_selector,'input[name*="checkout" i]','input[id*="checkout" i]','input[name*="departure" i]','input[id*="departure" i]']);if(!ci||!co)throw new Error('Hadaf check-in/check-out fields could not be detected');await fill(p,'guests',s.guests,[cfg.guests_selector,'select[name*="adult" i]','select[id*="adult" i]','input[name*="adult" i]','input[id*="adult" i]']);await fill(p,'rooms',s.rooms||1,[cfg.rooms_selector,'select[name*="room" i]','select[id*="room" i]','input[name*="room" i]','input[id*="room" i]']);const btn=await findVisible(p,[cfg.search_button_selector,'#btnSearch','input[value*="search" i]','button:has-text("Search")','a:has-text("Search")','input[type="submit"]']);if(!btn)throw new Error('Hadaf search button could not be detected');await btn.click({timeout:10000});}
function parseRate(text,def='AED'){const t=clean(text),m=t.match(PRICE_RE);if(!m)return null;const price=Number(clean(m[0]).replace(/,/g,'').match(/([0-9]+(?:\.[0-9]{1,2})?)/)?.[1]);if(!Number.isFinite(price)||price<=0)return null;const currency=(m[0].match(/AED|SAR|USD|EUR|GBP|PKR|US\$|\$/i)||[def])[0];return{price,currency:clean(currency),room:clean((t.match(/(?:Triple|Twin|Double|Single|Quadruple|Family|Deluxe|Standard|Superior|King|Queen|Suite|Apartment|Villa)[^|]*?(?:Room|Suite|Bed|Only|Included)?/i)||[''])[0]),board:clean((t.match(/Room Only|Breakfast Included|Bed and Breakfast|Half Board|Full Board|All Inclusive/i)||[''])[0]),cancellation:clean((t.match(/Non[- ]?refundable|Free Cancellation|Refundable/i)||[''])[0]),availability:clean((t.match(/Available|On Request|Sold Out|Not Available/i)||['Available'])[0]),raw:t};}
function hotelLike(t){t=clean(t);return Boolean(t&&t.length>=4&&t.length<=180&&!PRICE_RE.test(t)&&/hotel|resort|suites|residence|makkah|madinah|riyadh|jeddah/i.test(t));}
async function extractFrame(f,cfg){const body=await f.locator('body').innerText().catch(()=>''),lines=String(body).split(/\r?\n/).map(clean).filter(Boolean),out=[];for(let i=0;i<lines.length;i++){if(!PRICE_RE.test(lines[i]))continue;const w=lines.slice(Math.max(0,i-5),Math.min(lines.length,i+6)).join(' | '),r=parseRate(w,cfg.default_currency||'AED');if(r){let hotel='';for(let j=i-1,steps=0;j>=0&&steps<18;j--,steps++)if(hotelLike(lines[j])){hotel=lines[j];break;}out.push({hotel,...r});}}const rows=await f.locator('tr:visible').evaluateAll(rs=>rs.map(x=>clean(x.innerText||x.textContent||'')).filter(t=>t&&PRICE_RE.test(t))).catch(()=>[]);for(const row of rows){const r=parseRate(row,cfg.default_currency||'AED');if(r)out.push({hotel:'',...r});}return out;}
async function extract(context,cfg){const all=[];for(const p of context.pages())for(const f of allFrames(p))try{all.push(...await extractFrame(f,cfg));}catch{}const seen=new Set();return all.filter(r=>Number.isFinite(r.price)&&r.price>0).filter(r=>{const k=[clean(r.hotel),clean(r.room),clean(r.board),r.price,clean(r.currency),clean(r.cancellation)].join('|');if(seen.has(k))return false;seen.add(k);return true;}).slice(0,Number(cfg.max_results)||500);}
async function searchHadafSource(source,search){const cfg=source.browser_config||{};if(!source.login_url||!source.site_username||!source.site_password_enc)return{configured:false,results:[],error:null};let password;try{password=decrypt(source.site_password_enc);}catch(e){return{configured:true,results:[],error:`Credential decryption failed: ${e.message}`};}let browser,context;try{browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage();p.setDefaultTimeout(Number(cfg.timeout_ms)||15000);await p.goto(source.login_url,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(Number(cfg.initial_wait_ms)||2000);await blocked(p);await login(p,source,password,cfg);await searchPortal(p,search,cfg);await p.waitForTimeout(Number(cfg.results_wait_ms)||10000);await blocked(p);const results=(await extract(context,cfg)).map((r,i)=>({id:`${source.id}-${i}`,supplier:source.name,hotel:r.hotel||'Hotel',room:r.room||'',view:r.view||'',board:r.board||search.board||'',cancellation:r.cancellation||'',price:Number(r.price),currency:r.currency||cfg.default_currency||'AED',availability:r.availability||'Available',raw:r.raw||r,image:'',bookingUrl:''}));if(!results.length)return{configured:true,results:[],error:'Hadaf login/search completed but no priced rates were extracted'};return{configured:true,results,error:null};}catch(e){return{configured:true,results:[],error:e.name==='TimeoutError'?'Hadaf browser timed out':e.message};}finally{if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});}}
module.exports={searchHadafSource,healthHadafSource};