const CONNECTORS = [
  { id:'public-market',name:'Public Hotel Market',type:'public' },
  { id:'rezlive',name:'RezLive',type:'rezlive',urlEnv:'REZLIVE_API_URL',keyEnv:'REZLIVE_API_KEY',agentEnv:'REZLIVE_AGENT_CODE',userEnv:'REZLIVE_API_USERNAME',cityEnv:'REZLIVE_CITY_CODE',countryEnv:'REZLIVE_COUNTRY_CODE',nationalityEnv:'REZLIVE_GUEST_NATIONALITY' },
  { id:'b2b-bookings',name:'B2B Bookings',urlEnv:'B2B_BOOKINGS_API_URL',keyEnv:'B2B_BOOKINGS_API_KEY' },
  { id:'nowworld',name:'NowWorld',urlEnv:'NOWWORLD_API_URL',keyEnv:'NOWWORLD_API_KEY' },
  { id:'saltours',name:'SALTOUR',urlEnv:'SALTOURS_API_URL',keyEnv:'SALTOURS_API_KEY' },
  { id:'arabian-oryx',name:'Arabian Oryx',urlEnv:'ARABIAN_ORYX_API_URL',keyEnv:'ARABIAN_ORYX_API_KEY' },
  { id:'leamigo',name:'LeAmigo',urlEnv:'LEAMIGO_API_URL',keyEnv:'LEAMIGO_API_KEY' },
  { id:'locanda',name:'Locanda',urlEnv:'LOCANDA_API_URL',keyEnv:'LOCANDA_API_KEY' },
  { id:'babylon-holidays',name:'Babylon Holidays',urlEnv:'BABYLON_HOLIDAYS_API_URL',keyEnv:'BABYLON_HOLIDAYS_API_KEY' },
  { id:'peaceland-holidays',name:'Peaceland Holidays',urlEnv:'PEACELAND_HOLIDAYS_API_URL',keyEnv:'PEACELAND_HOLIDAYS_API_KEY' },
  { id:'holiday-begin',name:'Holiday Begin',urlEnv:'HOLIDAY_BEGIN_API_URL',keyEnv:'HOLIDAY_BEGIN_API_KEY' },
  { id:'ratehawk',name:'RateHawk',urlEnv:'RATEHAWK_API_URL',keyEnv:'RATEHAWK_API_KEY' },
  { id:'wanderbeds',name:'WanderBeds',urlEnv:'WANDERBEDS_API_URL',keyEnv:'WANDERBEDS_API_KEY' },
  { id:'mawasim',name:'Mawasim',urlEnv:'MAWASIM_API_URL',keyEnv:'MAWASIM_API_KEY' },
  { id:'webbeds',name:'WebBeds',urlEnv:'WEBBEDS_API_URL',keyEnv:'WEBBEDS_API_KEY' },
  { id:'tripovo',name:'Tripovo',urlEnv:'TRIPOVO_API_URL',keyEnv:'TRIPOVO_API_KEY' },
  { id:'expedia-taap',name:'Expedia TAAP',urlEnv:'EXPEDIA_TAAP_API_URL',keyEnv:'EXPEDIA_TAAP_API_KEY' },
  { id:'gatetours',name:'GateTours',urlEnv:'GATETOURS_API_URL',keyEnv:'GATETOURS_API_KEY' },
  { id:'rateloc',name:'RateLoc',urlEnv:'RATELOC_API_URL',keyEnv:'RATELOC_API_KEY' },
  { id:'anjum-hotel-makkah',name:'Anjum Hotel Makkah',urlEnv:'ANJUM_API_URL',keyEnv:'ANJUM_API_KEY' }
];

function configuredConnectors(){return CONNECTORS.map(c=>({id:c.id,name:c.name,configured:c.type==='public'||Boolean(process.env[c.urlEnv]),status:c.type==='public'?'public':process.env[c.urlEnv]?'ready':'awaiting_api'}));}
function xmlEscape(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function tag(xml,name){const m=xml.match(new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`,'i'));return m?m[1].trim():''}
function tags(xml,name){const re=new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`,'gi');const out=[];let m;while((m=re.exec(xml)))out.push(m[1].trim());return out}
function normalize(raw,connector,search){const items=Array.isArray(raw)?raw:(raw?.hotels||raw?.results||raw?.data||raw?.offers||raw?.properties||raw?.items||[]);if(!Array.isArray(items))return[];return items.flatMap((h,i)=>{const rooms=Array.isArray(h.roomDetails)?h.roomDetails:Array.isArray(h.rooms)?h.rooms:[h];return rooms.map((room,j)=>({id:String(room.bookingKey??room.booking_key??h.id??h.hotelId??h.hotel_id??h.code??`${connector.id}-${i}-${j}`),supplier:connector.name,hotel:h.hotel??h.hotelName??h.hotel_name??h.name??h.propertyName??'Hotel',room:room.room??room.roomName??room.roomType??room.room_type??room.room_name??h.room??'',board:room.board??room.boardName??room.boardType??room.board_type??room.mealPlan??h.board??search.board,price:Number((typeof room.price==='object'?room.price.total:room.price)??room.totalRate??room.totalPrice??room.total_price??h.price??h.totalPrice??h.total_price??h.amount??NaN),currency:(typeof room.price==='object'?room.price.currency:null)??room.currency??h.currency??h.currencyCode??h.currency_code??'',cancellation:room.cancellation??room.cancellationPolicy??room.cancelPolicy??h.cancellation??(room.freeCancellation?'Free cancellation':''),image:room.image??h.image??h.imageUrl??h.photo??'',bookingUrl:room.bookingUrl??h.bookingUrl??h.url??h.link??'',raw:h}))})}
async function callPublicMarket(search){const params=new URLSearchParams({destination:search.destination,checkIn:search.checkin,checkOut:search.checkout,guests:String(search.guests)});const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(`https://msos.ai/api/ai/search?${params.toString()}`,{headers:{Accept:'application/json'},signal:controller.signal});const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw new Error(`Public market returned invalid JSON (${response.status})`)}if(!response.ok)throw new Error(`Public market returned HTTP ${response.status}`);return{configured:true,results:normalize(data,CONNECTORS[0],search),error:null}}catch(e){return{configured:true,results:[],error:e.name==='AbortError'?'Public market timed out':e.message}}finally{clearTimeout(timer)}}
async function callRezLive(c,search){const url=process.env[c.urlEnv]||'http://test.xmlhub.com/testpanel.php/action/findhotel';const key=process.env[c.keyEnv]||'';const agent=process.env[c.agentEnv]||'';const user=process.env[c.userEnv]||'';const city=process.env[c.cityEnv]||'';if(!key||!agent||!user||!city)return{configured:false,results:[],error:null};const d1=search.checkin.split('-').reverse().join('/');const d2=search.checkout.split('-').reverse().join('/');const body=`<HotelFindRequest><Authentication><AgentCode>${xmlEscape(agent)}</AgentCode><UserName>${xmlEscape(user)}</UserName></Authentication><Booking><ArrivalDate>${d1}</ArrivalDate><DepartureDate>${d2}</DepartureDate><CountryCode>${xmlEscape(process.env[c.countryEnv]||'AE')}</CountryCode><City>${xmlEscape(city)}</City><GuestNationality>${xmlEscape(process.env[c.nationalityEnv]||'PK')}</GuestNationality><Rooms><Room><Type>Room-1</Type><NoOfAdults>${search.guests}</NoOfAdults><NoOfChilds>0</NoOfChilds></Room></Rooms></Booking></HotelFindRequest>`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','x-api-key':key,Accept:'application/xml,text/xml'},body:`XML=${encodeURIComponent(body)}`,signal:controller.signal});const text=await response.text();if(!response.ok)throw new Error(`Supplier returned HTTP ${response.status}`);const err=tag(text,'error');if(err)throw new Error(err);const currency=tag(text,'Currency')||'AED';const hotelBlocks=tags(text,'Hotel');const results=[];hotelBlocks.forEach((block,i)=>{const hotel=tag(block,'Name')||'Hotel';const hotelId=tag(block,'Id')||`${c.id}-${i}`;tags(block,'RoomDetail').forEach((room,j)=>results.push({id:tag(room,'BookingKey')||`${hotelId}-${j}`,supplier:c.name,hotel,room:tag(room,'Type')||'Room',board:tag(room,'BoardBasis')||search.board,price:Number(tag(room,'TotalRate')||tag(block,'Price')||NaN),currency,cancellation:tag(room,'TermsAndConditions')||'',image:'',raw:{hotelId,xml:room}}))});return{configured:true,results,error:null}}catch(e){return{configured:true,results:[],error:e.name==='AbortError'?'Supplier timed out':e.message}}finally{clearTimeout(timer)}}
async function callGeneric(c,search){const url=process.env[c.urlEnv];if(!url)return{configured:false,results:[],error:null};const key=process.env[c.keyEnv]||'';const headers={'Content-Type':'application/json',Accept:'application/json'};if(key)headers.Authorization=`Bearer ${key}`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{method:'POST',headers,signal:controller.signal,body:JSON.stringify(search)});const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw new Error(`Invalid JSON response (${response.status})`)}if(!response.ok)throw new Error(`Supplier returned HTTP ${response.status}`);return{configured:true,results:normalize(data,c,search),error:null}}catch(e){return{configured:true,results:[],error:e.name==='AbortError'?'Supplier timed out':e.message}}finally{clearTimeout(timer)}}
async function searchAll(search){const settled=await Promise.all(CONNECTORS.map(c=>c.type==='public'?callPublicMarket(search):c.type==='rezlive'?callRezLive(c,search):callGeneric(c,search)));const results=[],statuses=[];settled.forEach((r,i)=>{const c=CONNECTORS[i];statuses.push({id:c.id,name:c.name,configured:r.configured,ok:!r.error,error:r.error,status:r.configured?(r.error?'error':'live'):'awaiting_api'});results.push(...r.results)});results.sort((a,b)=>(Number(a.price)||Infinity)-(Number(b.price)||Infinity);return{results,statuses}}
module.exports={CONNECTORS,configuredConnectors,searchAll};
